"""adding one-to-many relationship (I hope)

Revision ID: 156eeaadb2c4
Revises: ce65c47e28d3
Create Date: 2022-11-07 18:09:03.762466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156eeaadb2c4'
down_revision = 'ce65c47e28d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'task', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
